### ISSUE TITLE
Emphasize -impute- option 

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#103]
We have received a few questions about the `impute` option in `xtevent` 2.0.0. I think we need to make this change more visible.

@Constantino-Carreto-Romero will:

- Add a short paragraph about impute in the home screen (about.md) (Do this on a branch)
- Create a short markdown describing imputation details. We'll eventually add a link to these from the home screen. (Do this on an issue folder, we'll find a place for it eventually).

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero still working on this.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero still working on this.

**Comment by jorpppp** [comment]
Pending.

**Comment by jorpppp** [comment]
Pending, should be done this week @Constantino-Carreto-Romero

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp, on the [homepage](https://github.com/JMSLab/xtevent/tree/issue103_emphasize_impute_option), 
- I added a paragraph about the impute option and highlighted that the user should use `impute(stag)` to have the results of xtevent 1.0.0.
- There, I added a link to a note about the `impute` option. I was writing it in markdown but I ran into the [markstat](https://data.princeton.edu/stata/markdown) command that helped me add some examples. I think we could use it for the examples on the homepage, as well.

**Comment by jorpppp** [comment]
@jorpppp  will review the note about the impute option here: https://raw.githack.com/JMSLab/xtevent/issue103_emphasize_impute_option/issue103/impute_option_description.html

**Comment by jorpppp** [comment]
Per call: It would be good to have the math behind this.

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/fe7fd51efdd0b06b7768b617babd9ce53cbff294 I implemented https://github.com/JMSLab/xtevent/issues/103#issuecomment-1284192661

It is pending https://github.com/JMSLab/xtevent/issues/103#issuecomment-1289525176

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero implemented the last formatting edits for these examples, so we are ready to pull.

**Comment by jorpppp** [comment]
Summary: In this issue we updated the Readme file to emphasize the `impute` option.

**Comment by Constantino-Carreto-Romero** [comment]
Summary: In this issue, we added a paragraph on the home page to emphasize the -impute- option and created an HTML file describing this option. 

Thread continues in https://github.com/JMSLab/xtevent/pull/121
