### ISSUE TITLE
Check possible issue with -nozeroline- and coefficient formatting options

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#105]
It seems like the -nozeroline- and coefficient formatting options may have been disabled in the last release. @Constantino-Carreto-Romero can you check if this is the case, please?

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Did you manage to check anything about this bug?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have not reviewed it, but I will do it today. I'm just preparing to upload the preliminary files for issue #59, so I can review issue #105 today.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I checked `xteventplot`'s appearance options and the ones not working were `nozeroline` and `nominus1label`. In https://github.com/JMSLab/xtevent/commit/530cff4c01ceaff320440b99da8281452d3f9c5d I fixed it.
These are examples to verify that they now work:
```stata
*install the xtevent version from the branch
net install xtevent, from("https://raw.githubusercontent.com/JMSLab/xtevent/issue105_some_plot_options_not_working") replace

*load example31.dta
use "https://github.com/JMSLab/xtevent/blob/main/test/example31.dta?raw=true", clear
xtevent y, panelvar(i) t(t) policyvar(z) window(5) 
xteventplot, nozeroline
xteventplot, nominus1label
```

**Comment by jorpppp** [comment]
Summary: In this Issue we fixed bugs related to some graph elements.
Thread continues in #106
