### ISSUE TITLE
Add support for `addabsorb` with proxies

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#11]

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero already fixed this bug with the absorb options in https://github.com/JMSLab/xtevent/commit/7f65e74128e72f4e874d8f4d8e51b20c68fe0f84 . He will add an example using these option combinations to the test file and then we'll review, pull and merge.

**Comment by jorpppp** [comment]
Summary: In this issue we fixed a bug that did not allow the usage of the addabsorb' option in iv estimation with proxies and reghdfe'
