### ISSUE TITLE
Take into account missing values in the check of the strongest lead 

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#110]
When `_eventiv` selects the lead of the differenced policy to use as an instrument, it does not check if there are missing values of the instrument. In short windows, the lead of the differenced policy may be missing for higher order leads, so comparing F-stats across regressions will be misleading. 

Make sure that regressions in the loop take into account possible missing values of the instruments and use the same sample.
Derived from #109 https://github.com/JMSLab/xtevent/issues/109#issuecomment-1261608505

**Comment by jorpppp** [comment]
Per call, we won't modify this code to select the strongest lead. We'll keep using the current code that chooses the strongest lead regardless of changes in sample across the first stage regressions.
