### ISSUE TITLE
Wording of warning

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#116]
When anticipatory effects are allowed we display a warning indicating which coefficient we normalize:

https://github.com/JMSLab/xtevent/blob/30656631e4dfe55c9aa8e0881184bd290167c9d3/xtevent/xtevent.ado#L174

I think the language "normalized to N" for N a lead may be confusing since it may suggest we're normalizing the coefficient to be equal to the value N rather than that we're normalizing (to a value of zero) the coefficient corresponding to lead N.

Maybe we should replace 

> so the coefficients were normalized to `norm'.

with something like

> ... so the coefficient at `norm` was selected to be normalized to zero

to be more in line with language elsewhere e.g.

https://github.com/JMSLab/xtevent/blob/30656631e4dfe55c9aa8e0881184bd290167c9d3/xtevent/xtevent.ado#L180

?

**Comment by jorpppp** [comment]
Sounds good, thanks @jmshapir. @Constantino-Carreto-Romero , can you implement please?

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/6c9327a1471126b36ad806d56e026d3224f528e4 I edited the message indicated in https://github.com/JMSLab/xtevent/issues/116#issue-1413793666. I checked in other parts of the ado files for other messages that could need to be changed as well, but I didn't find such messages. The new message in #114 considers this wording.
