### ISSUE TITLE
Integrate the documentation of the impute option to the repository

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#120]
Per comment https://github.com/JMSLab/xtevent/issues/103#issuecomment-1299301462, find a place in the repository for the documentation of the impute option.

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/3ae0c0f191b7c4ffddb2c09bd242f50810bd9bdc I uploaded:
- the file `create note about impute option using markstat.do`. With this file, `markstat` creates a smcl file and an html file. The html file is the final note about the impute option, that can be rendered with the help of `githack`: https://raw.githack.com/JMSLab/xtevent/issue120_integrate_impute_documentation/issue120/impute_option_description.html
- the file `impute_option_description.stmd`. This file is the input for the `markstat` package to create the html. See [here]( https://grodri.github.io/markstat/simpleScript) on how to create this file and [here ](https://grodri.github.io/markstat/gettingStarted)on markstat's prerequisites.
- The smcl and html files created by `markstat`.

**Comment by Constantino-Carreto-Romero** [comment]
On the home page, the link that redirects to the note about the impute option 
https://raw.githack.com/JMSLab/xtevent/issue103_emphasize_impute_option/issue103/impute_option_description.html needs to be updated, but this can be done only after finding a place in the repository for that HTML file.

**Comment by jorpppp** [comment]
As we work on the release in #109, I figure this is mostly done. @Constantino-Carreto-Romero can you please tell me what's pending here?

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero I modified the text for the imputation detail file a bit. Can you please rerun `markstat` on this and upload the updated html file in the issue folder?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp  in https://github.com/JMSLab/xtevent/commit/ed5a3abda50d022720c965dbe7521662ee298fdb I uploaded the updated html file after running `markstat` with the changes to the stmcl file in https://github.com/JMSLab/xtevent/commit/1303abc38b270d19eaac806aac1dc849beaeb098. 
In https://github.com/JMSLab/xtevent/commit/ed5a3abda50d022720c965dbe7521662ee298fdb I notice that the estimation results have changed, it might be due to a fixed bug in the meantime, but it seems strange that this also happened in the example when there is no imputation.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Thank you. I checked and the change in results is because of the bug fix in #126. There are some missing values in the dependent variables that made `xtevent`'s previous version drop some units. That's no longer the case.

Let me now move the html to a permanent location and I'll start a PR.

**Comment by jorpppp** [comment]
Summary: In this isse we reviewed the detailed documentation about the `impute` option and placed it in the main page.

Thread continues in #144
