### ISSUE TITLE
Implement creation of cohort and control cohort variables in SA

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#123]
Per https://github.com/JMSLab/xtevent/issues/35#issuecomment-1301644035 from #35: xtevent's SA should be able to create the cohort and control_cohort variables, so it is not necessary that the user has to create these variables, as in the actual setting (which mimics EventStudyInteract).

**Comment by jorpppp** [comment]
This was addressed in #179. Closing now.
