### ISSUE TITLE
Typo in xteventplot

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#130]
Per comment https://github.com/JMSLab/xtevent/issues/109#issuecomment-1440266068 in #109, there is a typo in xteventplot in line https://github.com/JMSLab/xtevent/blob/da196cc2d1b93ed3d9904a796fbcbec428d30b1c/xtevent/xteventplot.ado#L932

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero @santiagohermo. Looks like an easy fix but let me check if this is affecting anything else.

**Comment by jorpppp** [comment]
I fixed this in https://github.com/JMSLab/xtevent/commit/5ef9104fd14cd88b507730a9c8c71f28749daade. Seems like this is not affecting anything else because this Wald value is not used later in the code, but we should keep it for future bug checking just in case.

**Comment by jorpppp** [comment]
Summary: In this issue we fixed a typo in `xteventplot` regarding a Wald value. This does not affect any other calculation in the code.

Thread continues in #133
