### ISSUE TITLE
Revisiting imputation outside data window

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#15]
The package does some imputation for policy changes outside of the data window, motivated by the case of staggered adoption ([example](https://github.com/JMSLab/xtevent/blob/d48959fb3ff8bc67bc6891ba7b62ed05a536b4dd/xtevent/_eventgenvars.ado#L124)).

For each unit i, define F(i) as the first period in which we observe data for i, and L(i) as the last period in which we observe data for i.

I propose to refactor as follows:
* `default`: no imputation. (I believe this is currently implemented as `nostaggered`)
* `no_unobserved_change`: assumes that, for each unit i, the policy in periods t<F(i) is equal to z_{i,F(i)} and the policy in periods t>L(i) is equal to z_{i,L(i)}.
* `staggered`
  * checks for consistency with staggered adoption, which means
     * z_{i,t} \in {0,1}
     * z_{i,t'}>=z_{i,t} whenever t'>=t
  * if consistency fails, throws warning and reverts to `default`
  * if consistency holds
      * if z_{i,F(i)}=0 and z_{i,L(i)}=1 for all i then applies `no_unobserved_change`
      * otherwise applies `default`

I can imagine other versions being appealing so feel free to weigh in @SimonFreyaldenhoven @chansen776 @jorpppp if you see something you prefer.

**Comment by jorpppp** [comment]
Thanks @jmshapir. This refactoring sounds good to me. I have a couple of comments.

- For `staggered', I think we want to check that z_{i,t} is binary, not necessarily in {0,1}. In other words, we do not want to force the user to map their binary policy to {0,1}: instead we want the package to take the binary policy and produce properly-scaled estimates. I think _eventgenvars currently checks for a binary policy.
- A more substantive point is whether `xtevent' is currently deviating from the `staggered' behavior. I believe Veli and Nate played around with this already. Would they agree that the current default behavior of `xtevent' is what you call staggered, or are there any differences we need to keep in mind?

**Comment by jmshapir** [comment]
Thanks @jorpppp!

> * For `staggered', I think we want to check that z_{i,t} is binary, not necessarily in {0,1}. In other words, we do not want to force the user to map their binary policy to {0,1}: instead we want the package to take the binary policy and produce properly-scaled estimates. I think _eventgenvars currently checks for a binary policy.

I'm definitely fine with allowing other binary forms, e.g. {1, 2} instead of {0, 1}.

> * A more substantive point is whether `xtevent` is currently deviating from the `staggered' behavior. I believe Veli and Nate played around with this already. Would they agree that the current default behavior of `xtevent` is what you call staggered, or are there any differences we need to keep in mind?

@veli-m-andirin @nateschor is your understanding that under `staggered` option, `xtevent` behaves as described under the `staggered` bullet in https://github.com/JMSLab/xtevent/issues/15#issue-1145180171?

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir @jorpppp!

@jmshapir, I have two questions about the proposal in https://github.com/JMSLab/xtevent/issues/15#issue-1145180171.

On the following statement:

> checks for consistency with staggered adoption, which means
    - z_{i,t} \in {0,1}
    - z_{i,t'}>=z_{i,t} whenever t'>=t

For the second condition, how to deal with missing values, i.e. if there is a period t s.t. 1<=t<=T with a missing value, then are we going to ignore them or would this automatically translate as the failure of the second condition?

On this one:
> - if consistency holds
        -  if z_{i,F(i)}=0 and z_{i,L(i)}=1 then applies no_unobseved_change
        - otherwise applies default

Suppose that there are 40 units, for 39 of them we have z_{i,F(i)}=0 and z_{i,L(i)}=1, but for unit i' we have z_{i',t} = 0 for all t. Then should the package revert to `default` for all units? 

Other than that, on the question in https://github.com/JMSLab/xtevent/issues/15#issuecomment-1049234033, I think that there are differences with the current behavior and what is suggested in in https://github.com/JMSLab/xtevent/issues/15#issue-1145180171.

- The package currently seems to impute values that are "in the middle of the window", so it imputes more than missing end points.
- If the policy variable in the first period equals 1, then the package seems to assume that the policy change took place in the first period.

@jorpppp these are based on https://github.com/JMSLab/eventstudyr/issues/2#issuecomment-1046275575. For those who can not access the repo, [xtevent_staggered_test.txt](https://github.com/JMSLab/xtevent/files/8133360/xtevent_staggered_test.txt) contains a short "test" where these issues can be observed. Please let me know if I missed something.

**Comment by jmshapir** [comment]
Thanks @veli-m-andirin! On your questions:
* When checking consistency my proposal is to reject only when the data are inconsistent, and therefore not to reject any conditions due to missing values.
* I revised the proposal to make more explicit that we should apply the imputation to all units or none.

**Comment by jorpppp** [comment]
> Thanks @jmshapir @jorpppp!
> 
> @jmshapir, I have two questions about the proposal in [#15 (comment)](https://github.com/JMSLab/xtevent/issues/15#issue-1145180171).
> 
> On the following statement:
> 
> > checks for consistency with staggered adoption, which means
> > - z_{i,t} \in {0,1}
> > - z_{i,t'}>=z_{i,t} whenever t'>=t
> 
> For the second condition, how to deal with missing values, i.e. if there is a period t s.t. 1<=t<=T with a missing value, then are we going to ignore them or would this automatically translate as the failure of the second condition?
> 
> On this one:
> 
> > * if consistency holds
> >   -  if z_{i,F(i)}=0 and z_{i,L(i)}=1 then applies no_unobseved_change
> >   - otherwise applies default
> 
> Suppose that there are 40 units, for 39 of them we have z_{i,F(i)}=0 and z_{i,L(i)}=1, but for unit i' we have z_{i',t} = 0 for all t. Then should the package revert to `default` for all units?
> 
> Other than that, on the question in [#15 (comment)](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1049234033), I think that there are differences with the current behavior and what is suggested in in [#15 (comment)](https://github.com/JMSLab/xtevent/issues/15#issue-1145180171).
> 
> * The package currently seems to impute values that are "in the middle of the window", so it imputes more than missing end points.
> * If the policy variable in the first period equals 1, then the package seems to assume that the policy change took place in the first period.
> 
> @jorpppp these are based on [JMSLab/eventstudyr#2 (comment)](https://github.com/JMSLab/eventstudyr/issues/2#issuecomment-1046275575). For those who can not access the repo, [xtevent_staggered_test.txt](https://github.com/JMSLab/xtevent/files/8133360/xtevent_staggered_test.txt) contains a short "test" where these issues can be observed. Please let me know if I missed something.

Thank you @veli-m-andirin . @Constantino-Carreto-Romero will check these examples where -xtevent- may be imputing data in a different way from Jesse's proposal, and come up with possible solutions that we can discuss and eventually implement.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero has been familiarizing himself with `_eventgenvars` and he now understands how it works. He also read Schmideiny's paper. He'll be working now on implementing @jmshapir 's suggestion https://github.com/JMSLab/xtevent/issues/15#issue-1145180171 and on checking the issues brought up by @veli-m-andirin https://github.com/JMSLab/xtevent/issues/15#issuecomment-1049936885.

**Comment by Constantino-Carreto-Romero** [comment]
Right now, I’m working on the code implementation of issue [#15](https://github.com/JMSLab/xtevent/issues/15), about imputation outside of the observed data range for each unit. In the case of missing values in the policy variable z in the middle of the observed data range, these missing values will remain even after imputation under the staggered scenario. Ignoring these missing values would lead to a loss of observations.  When detecting these missing values, it might be helpful to launch a warning message such as “There are some missing values in policy z in the middle of the data range”.
While the user may impute these missing values manually, to make things easier for them, we were thinking of an option that lets the user impute values for policy z when these missing values follow a pattern:
In the staggered scenario, where the following conditions hold:
•	z_{i,t} \in {0,1}
•	z_{i,t'}>=z_{i,t} whenever t'>=t
and additionally, the following holds:
z_{i,F(i)}=0 and z_{i,L(i)}=1 for all i
where F(i) is the first period in which we observe data for i, and L(i) as the last period in which we observe data for i.
Suppose for a unit i’ and for some period of time [t’,t’’] within the observed data range, where t’<=t’’, we have missing values for the value of the policy z. If this missing value or group of contiguous missing values is neighbor of only 0’s or 1’s, i.e., z_{i’, t’-1}=0 and z_{i’, t’’+1}=0 or z_{i’, t’-1}=1 and z_{i’, t’’+1}=1, then impute the missing values with the corresponding value of the neighbors.
We also have a more general scenario that might be present in the data: suppose that for a unit i’ we have a data range [t’,t’’], where t’<t’’. Besides, there is at least a period t*, with t’<=t*<=t’’, where we do not observe the data for this unit. These observations will not be considered when estimating, as in the above scenario. In this case, it is not possible to propose a way to impute this missing data. In this scenario, it might be helpful to launch a warning message such as “there are some units with missing data for some periods”. This will make the user aware the estimations will be affected by these missing observations.

**Comment by Constantino-Carreto-Romero** [comment]
Right now, I’m working on the code implementation of issue [#15](https://github.com/JMSLab/xtevent/issues/15), about imputation outside of the observed data range for each unit. In the case of missing values in the policy variable z in the middle of the observed data range, these missing values will remain even after imputation under the staggered scenario. Ignoring these missing values would lead to a loss of observations.  When detecting these missing values, it might be helpful to launch a warning message such as “There are some missing values in policy z in the middle of the data range”.

While the user may impute these missing values manually, to make things easier for them, we were thinking of an option that lets the user impute values for policy z when these missing values follow a pattern:
In the staggered scenario, where the following conditions hold:
•	z_{i,t} \in {0,1}
•	z_{i,t'}>=z_{i,t} whenever t'>=t
and additionally, the following holds:
z_{i,F(i)}=0 and z_{i,L(i)}=1 for all i
where F(i) is the first period in which we observe data for i, and L(i) as the last period in which we observe data for i.
Suppose for a unit i’ and for some period of time [t’,t’’] within the observed data range, where t’<=t’’, we have missing values for the value of the policy z. If this missing value or group of contiguous missing values is neighbor of only 0’s or 1’s, i.e., z_{i’, t’-1}=0 and z_{i’, t’’+1}=0 or z_{i’, t’-1}=1 and z_{i’, t’’+1}=1, then impute the missing values with the corresponding value of the neighbors.

We also have a more general scenario that might be present in the data: suppose that for a unit i’ we have a data range [t’,t’’], where t’<t’’. Besides, there is at least a period t*, with t’<=t*<=t’’, where we do not observe the data for this unit. These observations will not be considered when estimating, as in the above scenario. In this case, it is not possible to propose a way to impute this missing data. In this scenario, it might be helpful to launch a warning message such as “there are some units with missing data for some periods”. This will make the user aware the estimations will be affected by these missing observations.

**Comment by jmshapir** [comment]
Thanks @Constantino-Carreto-Romero @jorpppp!

Regarding issuing a warning when z is missing inside the date range covered in the data, I am totally fine with that.

Regarding imputing z inside the date range, I'm somewhat hesitant to do this for two main reasons:
1. In cases where it is clearly appropriate, I'd bet that users will already have done it. (e.g., if I know that a law change occurred on a certain date, I will be able to fill in the binary z for all dates before and since, and so won't need the package to implement this for me). Note that this is a bit different from imputing outside the date range covered in the data, which almost by definition the user has not done, and which is relevant for `xtevent` because of the use of leads and lags of Delta(z).
2. In cases where it isn't clearly appropriate, it could lead to some weird side effects.

That said, as long as it's not a default, and it's clearly documented, I don't strongly oppose.

@SimonFreyaldenhoven @chansen776 let us know if you have views, too.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero some comments additional to the ones made on this commit: https://github.com/JMSLab/xtevent/commit/520a15e297d50a62d7638bf180be9b766fd2b189

- Is the `nodrop`option undocumented? Where is it coming from?
- We need to implement `nounobservedchange` as proposed by Jesse. Right now I think we only have `default' and `staggered'. We want to use those option names as well, instead of `impute`
- Check the endpoint cases where there are missing value in z in the middle.

**Comment by Constantino-Carreto-Romero** [comment]
In this [commit](https://github.com/JMSLab/xtevent/commit/bdd1cde7cb55414fa4fd72e0a23709def06cc1a7) we have already implemented the imputation options that @jmshapir proposed in this [post](https://github.com/JMSLab/xtevent/issues/15): default, no-unobserved-change, and staggered. We also added an extra option that builds upon the staggered option and additionally imputes missing values inside the observed data range of the policy variable only if the missing value(s) is (are) both preceded and followed by a state of unadopted policy (e.g., zero) or by a state of adopted policy (e.g., one) for that unit. 
In what follows, we are going to work on:
- Simplifying and clarifying the warning messages
- Making some blocks of code more efficient
- Grouping the imputation options into a single option with parenthesis, and inside the parenthesis, the users will specify which specific option they want
- Modifying the helpfile

**Comment by Constantino-Carreto-Romero** [comment]
Right now, we are working on these improvements:
-	Adding some warning messages about binary cases.
-	Sharpening the code that checks the third condition of the staggered option
-	Making code of binary checking more efficient
-	 Editing of helpfile

**Comment by jorpppp** [comment]
Some of the variables that are created in these imputation steps may be being stored as "double" when they could be stored as "int" to preserve space. We'll postpone checking that to issue #10 .

**Comment by jorpppp** [comment]
We are almost ready to wrap up this issue. We still need to check creation of the endpoint dummies when units are always-treated or never-treated, and we need to update the helpfile.

@jmshapir Once these two remaining tasks are done, @Constantino-Carreto-Romero  will start a PR here with me as a reviewer. I wanted to ask if @veli-m-andirin or @nateschor can pitch in as reviewers of this PR too. Since they've been working on these imputation issues their review may be useful here.

**Comment by jmshapir** [comment]
> I wanted to ask if @veli-m-andirin or @nateschor can pitch in as reviewers of this PR too. Since they've been working on these imputation issues their review may be useful here.

@veli-m-andirin @nateschor what do you think?

**Comment by nateschor** [comment]
> > I wanted to ask if @veli-m-andirin or @nateschor can pitch in as reviewers of this PR too. Since they've been working on these imputation issues their review may be useful here.
> 
> @veli-m-andirin @nateschor what do you think?

@jorpppp @Constantino-Carreto-Romero @jmshapir I'm happy to review!

**Comment by veli-m-andirin** [comment]
@jorpppp @Constantino-Carreto-Romero @jmshapir I'm happy to review, too!

**Comment by veli-m-andirin** [comment]
@Constantino-Carreto-Romero, thanks a lot for great effort here!

I wanted to raise a minor point: We typically close issues after a PR is opened for them. I can't close this one since I don't have write access to this repo. Could you take care of this?

**Comment by Constantino-Carreto-Romero** [comment]
I will take care of it.
Thank you @veli-m-andirin for the review.

**Comment by veli-m-andirin** [comment]
@jmshapir @jorpppp @Constantino-Carreto-Romero @nateschor @rcalvo12,

Reviving this thread! I have two questions after running this code snippet:

```
use analysis/release/exampleplots/simulation_data_dynamic.dta
xtevent y_base x_r, pol(z) panel(id) timevar(t) pre(2) post(3) overidpre(4) overidpost(5) norm(-3) plot savek(a)
```

1) What is the current default for imputation? I assume it is "doing nothing" (i.e. not imputing unless that option is specified, is that correct), is that correct?

If so, why is the third lead of the first differenced policy variable [here](https://user-images.githubusercontent.com/62054739/179049632-6c7049df-1305-4fc7-81f8-e98f9d51a2f4.PNG) is zero in periods 38,39,40 instead of missing?

2) After running this code, @nateschor and I have been getting [this plot](https://user-images.githubusercontent.com/62054739/179049929-7c8bdb67-c749-4b2e-9fa7-4215df1d941e.png). I wonder what does the reported mean on the left correspond to? If we follow the notation in the paper, I think it could be computed as:

```
by id: drop if a_eq_m3 == 0
collapse (mean) y_base
```

which gives -0.4274. (The mean of the outcome variable in units where there is a policy change three periods in the future.)  In fact, this is assuming that there are no policy changes outside the data window per the first bullet I outline. If we don't assume this, I think the corresponding calculation would be:

```
by id: gen firstdiff = z - z[_n -1]
by id: gen firstdiff_lead3 = firstdiff[_n + 3]
by id: drop if firstdiff_lead3 == 0
collapse (mean) y_base
```

which gives -0.276, which is also different from what is reported.

@jmshapir, I also wonder which computation you think would make more sense as the default for the mean we are reporting in the plots? I think the second one would make more sense if the default is not imputing anything, and maybe the first one would make more sense when impute option is specified.

**Comment by jmshapir** [comment]
> @jmshapir, I also wonder which computation you think would make more sense as the default for the mean we are reporting in the plots? I think the second one would make more sense if the default is not imputing anything, and maybe the first one would make more sense when impute option is specified.

@veli-m-andirin thanks! I could see a case for a variety of defaults, but maybe the simplest is to treat observed and imputed values of $z_{i,t}$ symmetrically for the purpose of the calculation in [(4)](https://scholar.harvard.edu/files/shapiro/files/eventstudy.pdf#page=7)?

**Comment by Constantino-Carreto-Romero** [comment]
@veli-m-andirin  Thanks for noticing these issues.
Regarding:
> 1. What is the current default for imputation? I assume it is "doing nothing" (i.e. not imputing unless that option is specified, is that correct), is that correct?

That's correct. The default is to do nothing, it imputes only if the option `impute` is specified. 

> If so, why is the third lead of the first differenced policy variable [here](https://user-images.githubusercontent.com/62054739/179049632-6c7049df-1305-4fc7-81f8-e98f9d51a2f4.PNG) is zero in periods 38,39,40 instead of missing?

When running:
```stata
use analysis/release/exampleplots/simulation_data_dynamic.dta
xtevent y_base x_r, pol(z) panel(id) timevar(t) pre(2) post(3) overidpre(4) overidpost(5) norm(-3) plot savek(a)
```
![screen](https://user-images.githubusercontent.com/36095845/179096922-4b6efc96-722d-4b05-8d61-218d26c1ca2d.png)

The endpoints are being correctly not imputed but the other event-time dummies are being imputed when they shouldn't. [Here ](https://github.com/JMSLab/xtevent/blob/a8952557ae9abf1ba4b08eb8e3c89d1dc844d6e8/xtevent/_eventgenvars.ado#L319) we should add a condition for imputing the other event-time dummies only if `impute` is specified. Should I open it as a new issue @jorpppp ?

> 2. After running this code, @nateschor and I have been getting [this plot](https://user-images.githubusercontent.com/62054739/179049929-7c8bdb67-c749-4b2e-9fa7-4215df1d941e.png). I wonder what does the reported mean on the left correspond to? If we follow the notation in the paper, I think it could be computed as:

The reported mean is calculated following [this code](https://github.com/JMSLab/xtevent/blob/a8952557ae9abf1ba4b08eb8e3c89d1dc844d6e8/xtevent/_eventols.ado#L272). What I notice here is that the mean is always being calculated using the original policy variable. It is also necessary to correct this, to use the imputed version of the policy variable when necessary.

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir @Constantino-Carreto-Romero!

@jmshapir, on https://github.com/JMSLab/xtevent/issues/15#issuecomment-1184969298: Can you please clarify treating observed and imputed values of  $z_{i,t}$ symmetrically, since I think in the default mode we are not imputing the policy variable?

**Comment by jmshapir** [comment]
> @jmshapir, on [#15 (comment)](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1184969298): Can you please clarify treating observed and imputed values of zi,t symmetrically, since I think in the default mode we are not imputing the policy variable?

@veli-m-andirin under my [proposal](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1184969298), in cases where we do not impute the policy variable, then we would use only observations ${i,t}$ with directly observed values of $z_{i,t}$ for the calculation in [(4)](https://scholar.harvard.edu/files/shapiro/files/eventstudy.pdf#page=7).

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir! Then, is it correct to say that for instance, in cases where we do not impute the policy variable, if we are normalizing the coefficient in front of the third lead of the first-differenced policy variable, then we should only use those observations where that lead is defined (and is non-zero)? (Note that in the example I posted in the first point [here](https://user-images.githubusercontent.com/62054739/179049632-6c7049df-1305-4fc7-81f8-e98f9d51a2f4.PNG)), $z_{i,t}$ is defined for $t\in{38,39,40}$ but $\Delta{z_{i,t+3}}$ should not be.)

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir! I think https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185847554 clearly explains what I had in mind in https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185603746, and for now I don't see cases where that proposal is ambiguous.
