### ISSUE TITLE
Inclusion of endpoints when executing xteventtest after adjusting with a linear trend

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#166]
After running `xtevent` with the `trend` option to adjust for a linear trend, when executing `xteventtest` the endpoints should not be considered in the tests. 

For instance, when executing:
```stata
*Setup
webuse nlswork, clear
*year variable has many missing observations.
*Create a time variable that ignores these gaps.
by idcode (year): gen time=_n
xtset idcode time
*Generate a policy variable that follows staggered adoption.
by idcode (time): gen union2 = sum(union)
replace union2 = 1 if union2 > 1
*Adjust the pre-trend by estimating a linear trend by OLS
xtevent ln_w age c.age#c.age ttl_exp c.ttl_exp#c.ttl_exp tenure , pol(union2) w(-5 9) cluster(idcode) impute(stag) trend(-4, method(ols) saveoverlay) 
```
If we then run:
```stata
*leveling off
xteventtest, overidpost(2)
```
we get:

![1](https://github.com/JMSLab/xtevent/assets/36095845/3ddbac7a-48cc-47ad-a13f-af78f002161f)

but the coefficients considered for the test should be `8` and `9`.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
- in https://github.com/JMSLab/xtevent/commit/1153e3aa257ea0fc14023b12c60819a6edd2eec7 I implemented small changes, so the endpoints are not considered in `xteventtest`'s tests.
- in https://github.com/JMSLab/xtevent/commit/ed64fdeda3b2fade92dc9d22f5c70f3a7640b511 I uploaded an issue folder with a do-file and its log-file where I tested `xteventtest` after changes in https://github.com/JMSLab/xtevent/commit/1153e3aa257ea0fc14023b12c60819a6edd2eec7. The only option [showing an error](https://github.com/JMSLab/xtevent/blob/ed64fdeda3b2fade92dc9d22f5c70f3a7640b511/issue166/test%20issue%20166.txt#L704) is `overid`. Nonetheless, I think it is an expected error because the option inherits `overidpre`'s value from `xtevent`'s call, which is stated in the [helpfile](https://github.com/JMSLab/xtevent/assets/36095845/754d6598-1e20-4501-9f01-ed4ba9d71ee6). Then, it tries to test pre-trends with that number of coefficients, but after the linear trend adjustment (with ols method), the number of pre-event coefficients available for the test is smaller.

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero . We should be able to adjust the value of overidpre and overidpost that xtevent will use if the xtevent call used the trend option. Why don't you give it a shot?

@jmshapir @SimonFreyaldenhoven FYI

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Yes, this sounds like a good plan. On some instances there won't be any coefficients available to test, in which case we may also want to have an informative error message.

**Comment by Constantino-Carreto-Romero** [comment]
update: I've not made progress, but I'm planning to retake today's afternoon.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
- in https://github.com/JMSLab/xtevent/commit/ea08baf5e7b211a3d0f0e01bd51cfa0e12e27730 I added some code to implement  https://github.com/JMSLab/xtevent/issues/166#issuecomment-1775458910 and https://github.com/JMSLab/xtevent/issues/166#issuecomment-1775465658
- in https://github.com/JMSLab/xtevent/commit/8e1a88bca3d995cccbb1210dea78024307e5757f  I updated the do file and its log file with examples to test the implementation.

**Comment by Constantino-Carreto-Romero** [comment]
Summary: In this issue, we made changes to `xteventtest`, so it doesn't use the endpoints in any of its tests if previously `xtevent` used linear trend adjustment. We also modified the number of coefficients it uses to test pre-trends in some cases if previously `xtevent` used linear trend adjustment with the ols method. 

Changes brought to main in https://github.com/JMSLab/xtevent/commit/4198174fab4a012e3ab69eca0b76f2ecc9199e40
