### ISSUE TITLE
prepare release

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#184]
In this issue, we'll update documentation for a new release. Version number pending. 

- [x]  Update home page
- [X]  Update version statements in ado files (done in https://github.com/JMSLab/xtevent/commit/6408fdc18b5af9899a83af33a012304a1f85f459) 
- [X]  Check examples in home page (note changes to `cohort` and `control_cohort` syntax in #179 (done in https://github.com/JMSLab/xtevent/commit/3553273802d820e9dcf098eb24e2ac1567167e31)
- [x]  Check examples in test file and run (done in https://github.com/JMSLab/xtevent/commit/9c71a620eb8d1bfab9d67b6a43c951d7735044a2)
- [x]  Check examples in help files and run
- [x]  Check that help files display properly
- [x]  Update acknowledgments (done in https://github.com/JMSLab/xtevent/commit/c969672e99215625f0d7a5d5c9b26d07eacc3a9b)
- [x] Update install.txt and release.txt (done in https://github.com/JMSLab/xtevent/commit/2a843bd9214e51a3a517bf83cd555cb8a883db6d)
- [X] Update version [dependencies ](https://github.com/JMSLab/xtevent/blob/main/dependency.do?rgh-link-date=2023-10-09T01%3A02%3A01Z)in dependency.do (done in https://github.com/JMSLab/xtevent/commit/f1e12ed827283f4bb71230f597bb9cb83e1da559)

**Comment by pxygithub2024** [comment]
Dear Jorge Eduardo Perez Perez,

I hope this message finds you well.

My name is Pan xy, and I am currently a Ph.D. student at Tsinghua University. I am encountering an issue when setting norm() to the first stage, norm(0). At the end of the process, I receive an r(198) error indicating that "_k_eq_m0 not found." Could you please advise me on how to address this situation?

Thank you very much for your help.

Best regards,
Pan xy

**Comment by jorpppp** [comment]
Dear Pan.

Thank you for your email. This was a previous issue in xtevent that was
fixed in issue #186

Error when normalizing `0` coefficient · Issue #186 · JMSLab/xtevent
(github.com) <https://github.com/JMSLab/xtevent/issues/186>

Can you please install the latest development version of xtevent and let us
know if the problem persists?

Thank you,

JPP

To install the last version in this repository, use the github command:
<https://github.com/JMSLab/xtevent#to-install-the-last-version-in-this-repository-use-the-github-command>

First, install the github command:

net install github, from("https://haghish.github.io/github/")

Then execute:

cap github uninstall xtevent

github install JMSLab/xtevent

**Comment by pxygithub2024** [comment]
Dear Mr.  Perez.
I followed the steps you mentioned and the error displayed is as follows:

. net install xtevent, from("
https://raw.githubusercontent.com/JMSLab/xtevent/master")
checking xtevent consistency and verifying not already installed...
could not copy https://raw.githubusercontent.com/JMSLab/xtevent/master/.
/xtevent/_eventivstatic.ado
(no action taken)
 I download the files from your github,and cover the old files in
my personal directory, But still don't work.Maybe I am doing something
wrong?

Thank you very much for your help.

Pan xy

Jorge Eduardo Perez Perez ***@***.***> 于2024年6月25日周二 05:05写道：

**Comment by pxygithub2024** [comment]
Dear Mr.  Perez.
I've solved the problem by following the steps you mentioned, it looks like
there should have been a problem with the network before, and I already had
to add the ",replace" option after the command. Thank you very much for
your help!
Pan xy


xingyu pan ***@***.***> 于2024年6月27日周四 23:55写道：

**Comment by jorpppp** [comment]
Per SemVer the new version is 3.1.0

**Comment by jorpppp** [comment]
Summary: In this issue we updated the home page and the repository for the 3.1.0 release.

Thread continues in XX
