### ISSUE TITLE
Error when normalizing `0` coefficient

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#186]
I'm getting an error when trying to set `norm(0)`. 

Below is a MWE based on the example in the help file.

Very possible this is just user error but wanted to flag in case not!

[norm0.log](https://github.com/JMSLab/xtevent/files/15142997/norm0.log)
[norm0.zip](https://github.com/JMSLab/xtevent/files/15143000/norm0.zip)

**Comment by jorpppp** [comment]
@jmshapir Thank, this looks like a bug, I was able to replicate it. I will start a branch to fix it.

**Comment by jorpppp** [comment]
@jmshapir Should be fixed now, starting a PR.
@Constantino-Carreto-Romero FYI

**Comment by jorpppp** [comment]
Summary: In this issue we fixed a bug where the temporary copy of the normalized event-time dummy was only generated correctly if the normalized coefficient corresponded to negative event-time.

Thread continues in #187
