### ISSUE TITLE
Left window of zero returns an error

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#188]
Per comment https://github.com/JMSLab/xtevent/pull/178#issuecomment-2093382033
When running 
```
use example31, clear
xtevent y, w(0 3) pol(z) impute(stag)
```
we got the following [error message](https://github.com/JMSLab/xtevent/assets/36095845/800e9f59-f4b1-4672-87fc-58edf3cc0fb2).

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
The error arose because the definition of some temporary variables was missing. We had defined them in the section code that generates the pre-event time dummies variables, but since in the case of left window = 0  that section code is never executed, we must also define the temporary variables in the section code that generates the post-event time dummies variables. Besides, the ordering of the left endpoint needed some adjustment to not assume that there is always at least one pre-event time dummy variable.

Bug fixed in https://github.com/JMSLab/xtevent/commit/4c3fa880a8ca2f87fbce7774b14cb4c3c47d1cb1 and https://github.com/JMSLab/xtevent/commit/fb9f1b59af42ac854726be41cfac2ac06a2cf5c7 

After, when running:
```
use example31, clear
xtevent y, w(0 3) pol(z) impute(stag) savek(aa)
```
I get the following [outcome](https://github.com/JMSLab/xtevent/assets/36095845/c117bda4-6ff4-45cd-b7dc-8976f30e05a0) and the event-time dummies variables are properly [ordered](https://github.com/JMSLab/xtevent/assets/36095845/b079cdc9-6787-41c4-92f1-a87b6b1901d3).

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero. I'm looking into the fact that plotting is not working now:

```
xtevent y, w(0 3) pol(z) impute(stag) plot
```

because there are no pre-event coefficients to test.

**Comment by jorpppp** [comment]
Summary: In this issue we addressed a bug when the user specified a left window of zero.
