### ISSUE TITLE
Option for adjusting text size of the test results in the plot

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#32]
Create an option for adjusting the text size of the test results in the plot.

**Comment by jorpppp** [comment]
@rayhuang11 will look into chapter 18 of the Stata User's guide to learn a bit more about Stata programming. 
@Constantino-Carreto-Romero and @rayhuang11 will also set up some time to talk about details of the -xtevent- code.

Afterwards, @rayhuang11 will modify -xteventplot.ado- to allow for an option to modify the style of these test results in the event-study plot. The code is in lines 445 - 447 and 527.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero thanks for your help. I've created a PR for this issue. Here is an example below of a font size adjusted plot:

<img width="979" alt="Screen Shot 2022-06-21 at 4 39 10 PM" src="https://user-images.githubusercontent.com/106756436/174893346-b05566e2-44d9-4931-9415-0f7e8b6e8f12.png">

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero we can review these changes (https://github.com/JMSLab/xtevent/commit/ea12af3c651acc9c59440547acb388672d2edc6b, https://github.com/JMSLab/xtevent/commit/d1ae25b7303b3429cfbd72071df7c000724c0b5c) in next week's meeting. The textbox option is working now. For example: 

<img width="903" alt="Screen Shot 2022-06-29 at 5 03 41 PM" src="https://user-images.githubusercontent.com/106756436/176544441-2b458598-7fe7-48e1-829b-74e5e80e15ed.png">

Question: do we want to include additional examples for the help file? 

Thanks!

**Comment by Constantino-Carreto-Romero** [comment]
@rayhuang11 It would be good to add an example to the help file. Likewise, you could add an example to the [test file](https://github.com/JMSLab/xtevent/blob/main/test/test.do).

**Comment by jorpppp** [comment]
Summary: In this issue we added options to format the text of the hypotheses test results below the graph.

Thread continues in #48
