### ISSUE TITLE
Switch default precision for parenthetical reference value

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#33]
Switch default precision for parenthetical reference value to four significant digits (rather than two decimal places)
(Requested enhancement from Roadmap)

**Comment by rayhuang11** [comment]
@jorpppp I've found both requested solutions to this issue. There seems to be an automatic way to set a "good precision." One setting allows us to use four significant digits; Stata chooses based on the number being displayed.

@jmshapir would you be able to give me write access to this repo? I can also show my solutions here first, if that's easier @jorpppp.

Thanks!

**Comment by jmshapir** [comment]
@rayhuang11 access elevated! Please use it wisely.

You can begin by creating a development branch for this issue using the functionality on the right of the screen:

![image](https://user-images.githubusercontent.com/7840353/174439894-2ea9e811-a95e-424e-bb66-e3faa96f683e.png)
