### ISSUE TITLE
 Implement estimation method that is robust to treatment effects heterogeneity

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#35]
Implement the estimation method that is robust to treatment effects heterogeneity, proposed by [Sun and Abraham (2021)](https://www.sciencedirect.com/science/article/abs/pii/S030440762030378X?via%3Dihub)
(Requested feature from Roadmap)

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero @jorpppp and @rayhuang11 will read Sun and Abraham.

**Comment by jorpppp** [comment]
We are still reading, hopefully we'll finish by the next meeting.

**Comment by jorpppp** [comment]
- [ ] @jorpppp reads Sun and Abraham

- [ ] @Constantino-Carreto-Romero reads Sun and Abraham

- [ ] @rayhuang11 reads Sun and Abraham

**Comment by rayhuang11** [comment]
Note that the [staggered package ](https://github.com/jonathandroth/staggered#stata-implementation)by Jonathan Roth implements the Sun and Abraham estimator in R.

**Comment by jorpppp** [comment]
We agreed that if the other packages that do Sun and Abraham are using R in the background, then it makes more sense to implement the Sun and Abraham estimator in Stata inside the xtevent architecture, instead of piggybacking on built-in Sun and Abraham commands. 
@rayhuang11  will check if there's an implementation of Sun and Abraham that uses Stata.

@jorpppp will find the code we used for cohort by cohort estimation in EventStudy, when we were doing synthetic control estimations. If we go down the road of writing SA ourselves, this will be the starting point.

**Comment by Constantino-Carreto-Romero** [comment]
I saw this [event study plot](https://twitter.com/Roxanagutz/status/1527690694801899521) on twitter. The plot was created using the [did_imputation stata package](https://github.com/borusyak/did_imputation), which includes a function to plot several models (it could be of interest to issue #7). For the creation of that plot, the did_imputation package doesn't embed Sun and Abraham, but the user separately uses the package [EventStudyInteract](https://github.com/lsun20/EventStudyInteract) which implements the estimator proposed in SA. Then, the coefficient vector and covariance matrix are passed to the [event_plot](https://github.com/borusyak/did_imputation/blob/main/event_plot.ado) function which can plot it, along with other models the user would like to add.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero 

[Here ](https://github.com/lsun20/EventStudyInteract)is the Stata package produced by Sun and Abraham to accompany their paper.

**Comment by jorpppp** [comment]
We are going to proceed in two steps:

1. We are going to estimate a basic event study using the EventStudyIntereact package and the example in our test file. That will help us understand how EventStudyInteract works. @rayhuang11 can work on this.
2. We are going to embed an `xtevent' estimation into the cohort loops that EventStudyInteract has. We'll work on this after completing 1.

**Comment by jorpppp** [comment]
Also look at https://github.com/JMSLab/EventStudy/blob/master/analysis/source/lib/stata/heterogeneous/sun_abraham.ado

**Comment by jorpppp** [comment]
@jorpppp  will check @rayhuang11 's example and then he'll figure out how to implement the 2nd step from https://github.com/JMSLab/xtevent/issues/35#issuecomment-1206652929 before handing it off to @Constantino-Carreto-Romero and @rayhuang11  again.

**Comment by jorpppp** [comment]
Per call: @Constantino-Carreto-Romero will check this: https://github.com/JMSLab/xtevent/issues/35#issuecomment-1213344734

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp  I have checked @rayhuang11's example and everything looks fine to me. It also helped me understand better the estimation steps, thanks. I'm going to start working on the second point from https://github.com/JMSLab/xtevent/issues/35#issuecomment-1206652929

**Comment by Constantino-Carreto-Romero** [comment]
I have checked https://github.com/JMSLab/xtevent/issues/35#issuecomment-1206663995. It is a program to estimate SA's estimator. Based on the comments in that program that describe its syntax, I estimated the example in https://github.com/JMSLab/xtevent/commit/54146593c330bf997d2b40743329e0431b77a2ca using both [sun_abraham.ado](https://github.com/JMSLab/EventStudy/blob/master/analysis/source/lib/stata/heterogeneous/sun_abraham.ado) and [EventStudyInteract](https://github.com/lsun20/EventStudyInteract). This is a [plot](https://user-images.githubusercontent.com/36095845/186810444-679b6915-db2c-45bc-9fa9-58331727e3d1.png) to compare the outcomes from both programs. I think I'm using the equivalent syntax in [sun_abraham.ado](https://github.com/JMSLab/EventStudy/blob/master/analysis/source/lib/stata/heterogeneous/sun_abraham.ado) to try to produce the same outcomes as with [EventStudyInteract](https://github.com/lsun20/EventStudyInteract), but the results differ. I need to explore more the options of the program to make sure I'm using the equivalent syntax. In case the syntax is correct, I could examine `sun_abraham.ado` to try to check if there are differences in the implementation compared to `EventStudyInteract`. 
Since `sun_abraham.ado` already implements SA's estimator, maybe we could embed a version of this program into `xtevent` and only add code to create the inputs it needs?

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero, we'll talk about this in today's call.

**Comment by jorpppp** [comment]
In last week's call, we agreed that we would look more into the differences between `eventstudyinteract` and `sun_abraham`. I think the approach in `eventstudyinteract`may be what we want to follow, just because it seems to be a more recent implementation. In any case, @Constantino-Carreto-Romero  will look at detailed output from both commands (using `trace`) and see if there are differences at the regression stage, or if they show up later in the codes.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero is still working on this.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp  I have explored the code in both [sun_abraham.ado](https://github.com/JMSLab/EventStudy/blob/master/analysis/source/lib/stata/heterogeneous/sun_abraham.ado) and [EventStudyInteract](https://github.com/lsun20/EventStudyInteract). I noticed many differences in the steps taken to estimate both the interacted regression and the cohort shares. However, they seem equivalent. Then, I looked at the regression stage, where they regress the outcome on the interactions between cohort indicators and relative time indicators. These are parts of the output of [sun_abraham.ado](https://user-images.githubusercontent.com/36095845/191375043-b0612710-c9ba-4f62-8b77-7be8ae4e8cdf.png) and [eventstudyinteract](https://user-images.githubusercontent.com/36095845/191375214-6f6d368a-969a-477d-a4f6-ec86c9397d69.png). For the model specification, I replicated the example in https://github.com/JMSLab/xtevent/issues/35#issuecomment-1228020467

**Comment by Constantino-Carreto-Romero** [comment]
Per call: @Constantino-Carreto-Romero will check the endpoint imputation in `sun_abaraham` and `EventStudyInteract` which could explain the differences in outputs in https://github.com/JMSLab/xtevent/issues/35#issuecomment-1252979027.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp  In https://github.com/JMSLab/xtevent/commit/fb8b34bd2f88bc1afd0588f4bf260113f4ae0e4e I re-estimated the example in https://github.com/JMSLab/xtevent/issues/35#issuecomment-1228020467, using the [example31](https://github.com/JMSLab/xtevent/blob/main/test/example31.dta) dataset and a window of (-3,4), plus the endpoints. 

[sun_abraham.ado](https://github.com/JMSLab/EventStudy/blob/master/analysis/source/lib/stata/heterogeneous/sun_abraham.ado) generates its event-time dummies and imputes them by default. In the case of [EventStudyInteract](https://github.com/lsun20/EventStudyInteract), I first generated the event-time dummies by `xtevent, impute(stag)` and then passed these variables to `EventStudyInteract`. By this, `sun_abraham.ado` and `EventStudyInteract` produces identical coefficient estimates (these are the coefficient estimates for
[sun_abraham.ado](https://user-images.githubusercontent.com/36095845/191621120-1df961ab-173a-4559-976a-50f248989879.png) and for [EventStudyInteract](https://user-images.githubusercontent.com/36095845/191621168-f839c767-4afd-451a-b7d2-b5a10e96fafb.png)). In the case of the standard errors, there are only small differences, where all `sun_abraham.ado`'s standard errors are smaller. These are the standard errors of [sun_abraham.ado](https://user-images.githubusercontent.com/36095845/191621725-1b4c60d5-9cd8-4369-a941-de8344a66da2.png) and [EventStudyInteract](https://user-images.githubusercontent.com/36095845/191621762-6ba8255a-ded6-4113-97a7-ba83db84f190.png). This is a [plot](https://user-images.githubusercontent.com/36095845/191626994-63ecd46b-de72-416c-9ead-652a693c5ae6.png) to compare both estimation results.

I checked for differences in the specification of the way to compute the standard errors, but in both cases, in the regression stage of the interactions, they cluster at the unit level (this is the specification I used for[ sun_abraham.ado](https://github.com/JMSLab/xtevent/blob/fb8b34bd2f88bc1afd0588f4bf260113f4ae0e4e/issue35/compare%20sun_abraham%20vs%20EventStudyInteract.do#L20) and for [EventStudyInteract](https://github.com/JMSLab/xtevent/blob/fb8b34bd2f88bc1afd0588f4bf260113f4ae0e4e/issue35/compare%20sun_abraham%20vs%20EventStudyInteract.do#L41)).

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero. I am glad that we found the source of the discrepancy. I am not concerned about these small differences in standard errors at this point.

We should go ahead and embed `xtevent` estimation inside EventStudyInteract. From our conversation, I would start by creating a `_eventsunabraham` command that is analogous to EventStudyInteract but estimates inside each loop with `_eventols`. We can build from that command in order to find out the options that it would need passed from `xtevent` to work properly, and the way to structure the output in order to use it with `xteventplot`.

**Comment by Constantino-Carreto-Romero** [comment]
> We should go ahead and embed `xtevent` estimation inside EventStudyInteract. From our conversation, I would start by creating a `_eventsunabraham` command that is analogous to EventStudyInteract but estimates inside each loop with `_eventols`. We can build from that command in order to find out the options that it would need passed from `xtevent` to work properly, and the way to structure the output in order to use it with `xteventplot`.

Great, I will start working on it.

**Comment by Constantino-Carreto-Romero** [comment]
I had some difficulties while trying to implement https://github.com/JMSLab/xtevent/issues/35#issuecomment-1254356406:

- We would like to replace the [regression step in EventStudyInteract ](https://github.com/lsun20/EventStudyInteract/blob/ca9a86bc7af94cf65dd1ac69fa734af382c37090/eventstudyinteract.ado#L85) with a call to `_eventols`. Nonetheless, the results brought by `_eventols` would be different from the ones needed by `EventSutdyInteract`: `_eventols` calls `_eventgenvars` to create event-time dummies and then `_eventols` use them to regress the outcome on them. However, `EventSutdyInteract` needs the output of a regression of the outcome on the interactions between event-time dummies and cohort indicators.
- When `EventSutdyInteract` calls `_eventols`, `EventSutdyInteract` has to specify several arguments needed by `_eventols` that require a previous check in `xtevent` (e.g. the estimation window). On the other hand, `EventSutdyInteract` requires a few arguments to be specified, several of which could be inferred within `_eventols` (e.g.  `absorb` can be inferred from `addabsorb`, `covariates` from `varlist`, `vce` from `options`). After this, `EventSutdyInteract` requires only two arguments to be defined: `cohort` and `control_cohort`.

Based on these two points, I think it could be manageable to embed `EventSutdyInteract` within `_eventols`. `_eventols` could be modified in the following [way](https://user-images.githubusercontent.com/36095845/192599030-742dc894-b9b9-4ba6-a597-c997d2b71ea4.png).

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero  I understand the limitations now and this plan looks good. My only comment is that the creation of the interactions between the event-time dummies and the cohort indicators should happen inside `event_genvars`.

**Comment by Constantino-Carreto-Romero** [comment]
in https://github.com/JMSLab/xtevent/commit/e1d2b215cadeec2e5e3d793ab698889bb2ccb8bf I embedded the `EventStudyInteract`'s code into `_eventols` following the proposed outline in https://github.com/JMSLab/xtevent/issues/35#issuecomment-1259854845

`xtevent` produces the same results as `EventStudyInteract`. For instance, running the following with `xtevent`:
```
*load example dataset
use "https://github.com/JMSLab/xtevent/blob/main/test/example31.dta?raw=true", clear
xtset i t

*generate variable of treatment time
gen timet=t if z==1
by i: egen time_of_treat=min(timet)
drop timet
*generate never treated indicator 
cap drop never_treat
gen never_treat=time_of_treat==.

xtevent y x, panelvar(i) t(t) policyvar(z) window(3) impute(stag) vce(cluster i) ///
   reghdfe cohort(time_of_treat) control_cohort(never_treat) 
xteventplot, noprepval nopostpval 
```
produces the following [output](https://user-images.githubusercontent.com/36095845/193178447-28806ca8-1e84-4ab4-bbba-b6259887a7a2.png), and running an equivalent specification with `EventStudyInteract`:
```
xtevent y, panelvar(i) t(t) policyvar(z) window(3) impute(stag) savek(g, noestimate)
eventstudyinteract y g_eq_m4-g_eq_m2 g_eq_p0-g_eq_p4, cohort(time_of_treat) ///
            control_cohort(never_treat) covariates(x)  ///
	    absorb(i t) vce(cluster i)
```
produces the following [output](https://user-images.githubusercontent.com/36095845/193178606-71d61e1c-7d62-476b-9e7e-f08130c1a290.png), which matches `xtevent`'s output.

As in `EventStudyInteract`, `cohort` and `control_cohort` have to be specified in `xtevent`. `reghdfe` also has to be specified to use the same estimation command as in `EventStudyInteract`, 

`xteventplot` can also be executed and produces the following [plot](https://user-images.githubusercontent.com/36095845/193180639-b70dccc2-809b-48b3-a79e-7304bb4538c5.png). Nontheless, it still cannot show the tests' output. 

Options such as `diffavg`, trend adjustment by GMM, etc. and command `xteventtest` cannot be executed yet. There is an incompatibility issue between the output expected by these options/commands and the output produced by SA' estimation procedure. For instance, the trend adjustment by GMM expects a regression output, so it can take the whole vector of coefficients of both event-time dummies and controls, then adjust these coefficients, and finally replace the regression's original coefficients with these new coefficients. However,  SA's procedure doesn't create a regression output, but a vector of coefficients and covariance matrix, and only for the event-time dummies. To overcome this, so trend adjustment by GMM could be used, I was thinking of estimating a counterfactual regression with xtevent, then replacing event-time dummies' coefficients with the ones from the SA's procedure, and then passing this regression output to the code for the trend adjustment by GMM. I'm not sure whether this is correct because in the regression output passed to adjustment by GGM we would be mixing coefficients from SA's procedure (the event-time dummies) and coefficients from the baseline estimation (the controls).

**Comment by jorpppp** [comment]
Per call: We will work on handling the output from `EventStudyInteract`to be compatible with output from `xtevent`. That way, all the post-estimation functions from `xtevent` should work.

**Comment by Constantino-Carreto-Romero** [comment]
>  To overcome this, so trend adjustment by GMM could be used, I was thinking of estimating a counterfactual regression with xtevent, then replacing event-time dummies' coefficients with the ones from the SA's procedure, and then passing this regression output to the code for the trend adjustment by GMM. I'm not sure whether this is correct because in the regression output passed to adjustment by GGM we would be mixing coefficients from SA's procedure (the event-time dummies) and coefficients from the baseline estimation (the controls).

update: I'm currently working on making compatible the output from `EventStudyInteract` with the output from `xtevent`. I'm following that outline.

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/a9ed6df799c86072488aecb2691206eab825c7c1 I added some code, so now the postestimation options, such as `diffavg` and trend adjustment by GMM are enabled. `xteventplot` and `xteventtest` can also be executed properly. To make compatible the output from SA with `xtevent`, I followed the outline described at the end of https://github.com/JMSLab/xtevent/issues/35#issuecomment-1263064646. I have not implemented https://github.com/JMSLab/xtevent/issues/35#issuecomment-1260108309 yet, I think to try to generate the interaction variables in `_eventgenvars` could be difficult because these variables should be added to the database, so `_eventols` can use them, later. 

In https://github.com/JMSLab/xtevent/commit/e19c37ff413fa82f2f8dd663b8a9c29ee31d3584, I added some examples to check the implementation. I attach their [log file](https://github.com/JMSLab/xtevent/files/9759332/issue35_examples.log).

**Comment by jorpppp** [comment]
@jorpppp  Will check this code

@Constantino-Carreto-Romero  will add cohort-level estimates and their standard errors (or variance matrices) as outputs that the user can access, should they want to do so.

@jorpppp will download the simulated datasets with Heterogeneous Treatment effects from the EventStudy repo, and send them to @Constantino-Carreto-Romero. @Constantino-Carreto-Romero will run analogous tests on these datasets. We expect that the results from `xtevent` using the SA estimator vs. using TWFE should be quite different.

**Comment by jorpppp** [comment]
> @Constantino-Carreto-Romero I understand the limitations now and this plan looks good. My only comment is that the creation of the interactions between the event-time dummies and the cohort indicators should happen inside `_event_genvars`.

I agree that since the set of cohort variables interacted with the time dummies has a large number of variables, it's convenient to have these variables be temporary. The code is now generating these temporary variables in `_eventols`. 

We should enable an option for the user to keep these interacted variables in the dataset if they want to. @Constantino-Carreto-Romero will add this option.

**Comment by Constantino-Carreto-Romero** [comment]
update: I'm currently working on this issue

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/85ae3976f6164f59e5a1bdea050d4f94d6e52e09 I implemented: 

- https://github.com/JMSLab/xtevent/issues/35#issuecomment-1275232678 about `xtevent` producing other outputs `EventStudyInteract` produces as well. These are matrices of: i) cohort-relative time effects; ii) variance of cohort-relative time effects; iii) cohort shares; iv) variance of cohort shares.
- https://github.com/JMSLab/xtevent/issues/35#issuecomment-1275239731 the option `SAVEINTeract` let the user save the interactions with a prefix. For instance, for cohort 3 and relative time -2, its interaction variable is saved as prefix_m2_3

In https://github.com/JMSLab/xtevent/commit/97f5ae401fe1f61746d0ffd648cf27c7e545632d I added some examples to check these implementations. In https://github.com/JMSLab/xtevent/commit/7d26fa5f56013a4e215efcaec7d696f4c6df22e5 I added the log file.

**Comment by jorpppp** [comment]
Per call, the option  `saveinteract` will become a suboption of `savek`.

**Comment by Constantino-Carreto-Romero** [comment]
update: I'm currently working on this issue

**Comment by Constantino-Carreto-Romero** [comment]
In https://github.com/JMSLab/xtevent/commit/1e1e4796210c2405ee0a91cf791a87da0692afe1 I implemented https://github.com/JMSLab/xtevent/issues/35#issuecomment-1284170149. 

In https://github.com/JMSLab/xtevent/commit/2b1aea04a7874b945010f559717e486a98ca3a7d I added some examples to the example file to check the implementation of https://github.com/JMSLab/xtevent/issues/35#issuecomment-1284170149. I uploaded the log file as well.

In https://github.com/JMSLab/xtevent/commit/f14f510757004366e5475a1606625cda04c07b83 I created a dataset with treatment effects heterogeneity. For this, I replicated the example code in [this repository](https://github.com/borusyak/did_imputation/blob/main/five_estimators_example.do). Then, in the same file, I added some code to create [this plot](https://user-images.githubusercontent.com/36095845/197458063-afa712f8-2c73-47f9-86f3-27776e696e11.png) to compare `xtevent`'s ols vs `xtevent`' SA.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp in https://github.com/JMSLab/xtevent/commit/2548f1763fffcfae12fd4569844577249588210c I added some examples to the help file; in https://github.com/JMSLab/xtevent/commit/c1bdf8085b5c781fed4898496beb9e8b7b08d21f I added an example to the home page and; in https://github.com/JMSLab/xtevent/commit/83a3cfe33c2b35da6ff4b5430773b8223fe27834 I added examples to the test file. I checked that in each case the examples run properly.

**Comment by Constantino-Carreto-Romero** [comment]
Per call, @Constantino-Carreto-Romero will:
- In the message telling that the event-time coefficients are being estimated by the Interaction Weighted Estimator, be more informative and specify that it is SA's estimator.
- Recreate the log file using a dataset with a greater number of observations per cohort. With this, `xtevent` and `EventStudyInteract` should produce very similar outputs with the example31 dataset
- Attach the graphs that were produced in the [code to check the implementations](https://github.com/JMSLab/xtevent/blob/issue35_implement_estimation_robust_treatment_heterogeneity/issue35/issue%2035%20examples%20to%20check%20implementation.do) and which are not shown in the log file
- in the help file, as in the case of the option `control_cohort`, specify that the option `control` is required for SA estimation
- open an issue as enhancement where xtevent's SA should be able to create the `cohort` and `control_cohort` variables, so it is not necessary that the user has to create these variables, as in the actual setting (which mimics `EventStudyInteract`'s setting).
- update the Acknowledgements in the help file
- open the PR

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp :
> * In the message telling that the event-time coefficients are being estimated by the Interaction Weighted Estimator, be more informative and specify that it is SA's estimator.

In https://github.com/JMSLab/xtevent/commit/d06b870d9040494368d0c067a6d8282d7cb51483, I implemented it.

> * Recreate the log file using a dataset with a greater number of observations per cohort. With this, `xtevent` and `EventStudyInteract` should produce very similar outputs with the example31 dataset

In https://github.com/JMSLab/xtevent/commit/6179d2fc456832ab330fbf11ff2319007774f1fa, I added to the examples to check the implementation, estimations with different sample sizes: results indicate that as the number of observations per cohort increases, the coefficients from xtevent's default and xtevent's SA are more alike. Here I'm using the dataset without heterogeneous treatment effects from [this code](https://github.com/JMSLab/xtevent/blob/issue_59-allow-for-data-structures-that-cannot-be-xtseted/issues/59/Example31SimulateData.do) in #59 .

> * Attach the graphs that were produced in the [code to check the implementations](https://github.com/JMSLab/xtevent/blob/issue35_implement_estimation_robust_treatment_heterogeneity/issue35/issue%2035%20examples%20to%20check%20implementation.do) and which are not shown in the log file

These are the graphs: [adj_trend](https://user-images.githubusercontent.com/36095845/202200098-a560463e-4215-4872-a180-242f93f90fe3.png), [overlay_trend](https://user-images.githubusercontent.com/36095845/202200142-4541a5bc-880d-4909-b119-a3e1e8436bd5.png), and [smpath](https://user-images.githubusercontent.com/36095845/202200231-5f874128-801f-4b0d-be12-5c29992a4b9e.png). From the check with different sample sizes: [_1000](https://user-images.githubusercontent.com/36095845/202200447-41da5844-5065-4cfa-8357-de46d3543ee2.png), [_10000](https://user-images.githubusercontent.com/36095845/202200555-1071fcec-a427-4810-b194-b70c827e0592.png), and [_50000](https://user-images.githubusercontent.com/36095845/202200589-6f8774d5-1690-492b-82b6-6cc8036afcab.png).

> * in the help file, as in the case of the option `control_cohort`, specify that the option `control` is required for SA estimation

In https://github.com/JMSLab/xtevent/commit/467cca07f153b9b7edde3a157631b099e99350d5, I implemented it.

> * open an issue as enhancement where xtevent's SA should be able to create the `cohort` and `control_cohort` variables, so it is not necessary that the user has to create these variables, as in the actual setting (which mimics `EventStudyInteract`'s setting).

https://github.com/JMSLab/xtevent/issues/123

> * update the Acknowledgements in the help file

In https://github.com/JMSLab/xtevent/commit/467cca07f153b9b7edde3a157631b099e99350d5, I implemented it.

> * open the PR
