### ISSUE TITLE
Allow static overlay when the impute option has been used 

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#46]
After executing `xtevent` with the `impute` option, calling` xteventplot, overlay(static)` shows an error. This happens because `overlay(static)` needs the imputed policyvar to be available in the database. Nonetheless, the imputed policyvar is available only if the user specified the `saveimp` suboption within the `impute` option.

**Comment by jorpppp** [comment]
Summary: In this issue we fixed a bug with static overlay plots when the policy variable was imputed. 

Thread continues in #50
