### ISSUE TITLE
Trend extrapolation in scenarios without binary policy variables - linear trends

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#5]
xtevent 1.0.0 allows for extrapolation of a linear trend in event-time as in Dobkin et al. (2018) for scenarios with binary policy variables . Extend this functionality to allow for extrapolation of higher-order trends and for settings with continuous policy variables. To do that, fit the trend to pre-event cofficients using GMM estimation.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero in https://github.com/JMSLab/xtevent/commit/f859b837807078abba58d86fb3737e016a0b401f I uploaded the test file for trend extrapolation.
@Constantino-Carreto-Romero will study this along with the notes for gmm trend extrapolation [here](https://github.com/JMSLab/EventStudy/blob/8805b361838c62bd86f5abcdb5bf42f468422ee8/issues/106/extrapolation.pdf) and then he will finish up embedding this into the `xtevent` code.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will check that event-time is generated when imputation is `nuchange` or when there is no imputation.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will check

- [ ] That the current implementation of the gmm trend works when controls are added to the regression (check if the standard errors on the controls change between the regression implementation and the gmm implementation)
- [ ] Write the code to call the gmmtrend option from `xtevent`. `trend` should allow both a reg and a gmm option, and gmm should be the default.
- [ ] Start thinking and implementing the case when the normalized coefficient is not -1.

**Comment by Constantino-Carreto-Romero** [comment]
So far, I have: 
1) Checked [the issue with the generation of the event-time variable](https://github.com/JMSLab/xtevent/issues/5#issuecomment-1128211667), now it is generated only when the policyvar is binary and satisfies no-reversion. I also edited the error message when the user specifies the option `trend` but the policivar doesn't satisfy these conditions; 
2) revisited the gmm code and the mata function embedded in `_eventols.ado` that computes de adjusted coefficients and variances: 
3) the code reposted the estimations of coefficients and covariances, replacing them only for the coefficients that show up in the plot. I have added to the mata function the code to compute the adjusted covariances for all the independent variables in the regression. Now, I'm making the code to repost using this covariance matrix. Replacement for this matrix is necessary to have the adjusted covariances of the controls.

**Comment by Constantino-Carreto-Romero** [comment]
Current progress:
1. Now the code reposts estimations using the covariance matrix for all the independent variables.
2. GMM adjustment accounts for the inclusion of controls (point 1 of [task list](https://github.com/JMSLab/xtevent/issues/5#issuecomment-1128221290)).
3. There is only one trend option, `trendg` (temporal name), that parses two suboptions, `reg` (linear trend) and `gmm` (gmm adjustment). `gmm` is the default. This is point 2 of [task list](https://github.com/JMSLab/xtevent/issues/5#issuecomment-1128221290).

I will be working on:
1. xteventplot should let an overlay plot for trend extrapolation in the gmm case as well.
2. adjust the way xteventplot creates the overlayplot in the linear case.

**Comment by Constantino-Carreto-Romero** [comment]
Current progress:
1. Now `xteventplot` lets overlay plots for both gmm or regression methods.

I will be working on:
1. Currently overlay estimations for the trend case are always generated when running the `xtevent` command with the option `trend`. The `trend` option should have a suboption that allows the user to decide whether the estimations for the overlay plot should also be generated. `xteventplot` should show an error message if we ask for it to create an overlay plot but previously we didn't generate the overlay estimations when calling the `xtevent` command with the `trend` suboption.

We will postpone for the next release working on the following enhancements related to this issue:
1. Trend extrapolation for the case when normalization is different from -1.
3. GMM estimation with higher degree trends. Currently, we are using linear trend.

**Comment by Constantino-Carreto-Romero** [comment]
Current progress:
Now `trend`  has the suboption `saveoverlay` that lets specify whether to estimate the coefficients and trend for the overlay plot. `xteventplot` produces the overlay plot only if previously `xtevent` was executed with the suboption `saveoverlay`.

I will be working on:
Some corrections of the helpfiles of `xtevent` and `xteventtest`.

We will postpone for the next release working on the following enhancement related to this issue:
Allow testing for a linear trend generated with gmm

**Comment by jorpppp** [comment]
Summary: In this issue we implemented GMM trend estimation to extrapolate linear trends when the policy variable is not binary.

Thread continues in #41.

Additional features related to trend extrapolation will be implemented in #37, #38, and #39
