### ISSUE TITLE
Upload xtevent 2.0.0 to SSC

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#54]
I have been trying to submit the new release xtevent 2.0.0 from here to SSC; https://github.com/JMSLab/xtevent/releases/tag/v2.0.0

However Gmail is bouncing the zip file back and flagging it as a virus! I know our code is not perfect, but that seems harsh.

@Constantino-Carreto-Romero can you check if you also get the false positive when trying to send the zip file from the release as an attachment? If so, can you try zipping the files yourself to see if you get the same behavior? I am trying to rule out that the issue is from my computer's side.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have tried to attach the zip file from https://github.com/JMSLab/xtevent/releases/tag/v2.0.0 and I get the same error "virus detected". Then, I tried downloading the files from the repository, zipping them, and attaching them, but there it shows the same virus message.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Thanks. I changed the file in the release (different compression method). Can you try that one?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp 
Zipping them with a ".rar" extension worked on my computer
https://drive.google.com/drive/folders/1898TyoMKE4WBbywhU2wzBAjI2nu5XbNz?usp=sharing

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero unfortunately SSC guidelines ask for .zip or .gz

http://repec.org/bocode/s/sscsubmit.html

Did you try the new file in the release?

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp with the new file it works

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Thanks, I'll close the issue when SSC confirms the new version is posted.

**Comment by jorpppp** [comment]
It's up, although we may need to update soon because of #55
