### ISSUE TITLE
Check option abbrevations in all commands

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#56]
Check option abbreviations in `xtevent`, `xteventplot` and `xteventtest`. Check that all parsers understand the abbreviations and check if we want to enable new abbreviations.

**Comment by jorpppp** [comment]
@rayhuang11 will
- [ ] Check `xtevent`, `xteventplot` and `xteventtest` to allow for more abbreviations in the options.
- [ ] Make sure that the abbrevations are consistent across commands.
- [ ] Check the lower level commands and parsers to make sure they allow abbreviations as well.

Make sure

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero I added some additional abbreviation options and checked consistency of abbreviations of across different ado files. We can discuss tomorrow whether we like the abbreviations I chose.

**Comment by jorpppp** [comment]
@rayhuang11 will implement some minor abbrevation changes

**Comment by rayhuang11** [comment]
@jorpppp one minor thing:

I noticed in some files (e.g. `_eventiv.ado`) the option to absorb additional variables in reghdfe is called `ABSorb(string)`. However, in `xtevent.ado`, it is called `ADDABSorb(string)`. Should we make them consistent?

**Comment by jorpppp** [comment]
@rayhuang11 Yes, we should maintain consistency. Can you fix that, please? @Constantino-Carreto-Romero can you check that after @rayhuang11 is done.

Something I've noticed: We are still discussing in the issues after a PR has been created. Once a PR has been created, we should move discussion to the PR. This is my last comment on the Issue and we'll keep discussing this on the PR.

**Comment by jorpppp** [comment]
Summary: In this issue we checked option abbreviations.

Thread continues in #64.
