### ISSUE TITLE
Installing the Github version of the package from inside Stata

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#58]
@Constantino-Carreto-Romero will look at how we can enable installation from Github inside Stata, as `reghdfe` does. We may need to program a package file. There may also be an alternative using a stata command to install from Github.

**Comment by jorpppp** [comment]
We want to do this before the next release. We'll also modify the repository readme to reflect this when we figure it out.

**Comment by Constantino-Carreto-Romero** [comment]
Installation from github has been enabled by two ways: 1) by the `github` command and; 2) by the `net` command (as for `reghdfe`).
I consulted the following sources:
- https://www.stata.com/manuals/rnet.pdf
- http://users.jyu.fi/~mivaanro/github/
- https://github.com/sergiocorreia/reghdfe

**Comment by Constantino-Carreto-Romero** [comment]
> @Constantino-Carreto-Romero this did not work from me. The address `https://raw.githubusercontent.com/JMSLab/xtevent/issue58_installation_from_github` seems to be invalid. But I think this may be due to Banco de Mexico's firewalls, because installing reghdfe this way also fails.

I installed `reghdfe` with a similar syntax, as described in the [repository of reghdfe](https://github.com/sergiocorreia/reghdfe), and it worked on my computer.

> When I try `net install xtevent, from("https://github.com/JMSLab/xtevent/tree/issue58_installation_from_github")` I get a "Nothing to install" error message. Any ideas as of why this second address would not work?

I think it doesn't return an error because the URL exists and it found the files in that URL, but the downloadable versions of the ado files are not stored in the `github.com` domain, but in the `raw.githubusercontent.com`  domain. It is what I understand from this [forum](https://stackoverflow.com/questions/39065921/what-do-raw-githubusercontent-com-urls-represent).

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero got it, thanks. I think we'll have to rely on testing from @rayhuang11 , because there's no way for me to test it for me.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero sorry for the delay on my end!

For me, `net install xtevent, from("https://raw.githubusercontent.com/JMSLab/xtevent/issue58_installation_from_github") replace` works! No issues at all. 

Thanks.

**Comment by jorpppp** [comment]
Great, thanks @Constantino-Carreto-Romero  @rayhuang11.  I'll make some minor edits to the mardown and then I'll merge this in.

**Comment by jorpppp** [comment]
Summary: In this issue we enabled installation from Github inside Stata and updated the readme file.

Thread continues in #61.
