### ISSUE TITLE
Add release information to .txt file to be included in each releases's zip file

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#60]
Right now every release includes a [install.txt](https://github.com/JMSLab/xtevent/blob/aa58dd023672e42351d89580f5f116106dc2106a/xtevent/install.txt) file.

We should also create a "release.txt" file that includes version information and the change log from the release page: https://github.com/JMSLab/xtevent/releases/tag/v2.0.0. That way, if a user downloads the zip file, it will include release information.

@rayhuang11  can you draft a version of this txt file, please?

**Comment by jorpppp** [comment]
Rough draft of release.txt:

xtevent 2.0.0 - Date of release. 

by authors

to cite, cite (Paper citation)

Changelog:

Info from the release (broad changes, not the detailed ones)

**Comment by rayhuang11** [comment]
@jorpppp the draft is in XX. I've attached a few questions to it. Please let me know your thoughts. Thanks!

**Comment by jorpppp** [comment]
@rayhuang11 Thank you. I answered the questions on Github comments as well.

**Comment by rayhuang11** [comment]
Summary: in this issue, we created a "release.txt" file that includes version information and the change log from the release page: https://github.com/JMSLab/xtevent/releases/tag/v2.0.0.

Thread continues in
