### ISSUE TITLE
Statalist

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#62]
@jorpppp will post info about the new release and the Github repo on Statalist.

@rayhuang11 will check Statalist for discussion about `xtevent` and bring in any issues that we may want to work on.

**Comment by jorpppp** [comment]
@rayhuang11 any issue that you find, just copy it here and we'll discuss whether we want to create new issues.

**Comment by rayhuang11** [comment]
@jorpppp 

No bugs / suggestions have been reported for `xtevent` on Statalist.

When we search "xtevent" on Statalist we get 2 threads, one of which is the [original post](https://www.statalist.org/forums/forum/general-stata-discussion/general/1627508-xtevent-stata-module-to-estimate-and-visualize-linear-panel-event-study-models-now-available-on-ssc) that Jorge shared about `xtevent`. In the discussion thread, people have asked questions about `xtevent` (e.g. the `window` option), but there have not been any issues.

Another user mentioned `xtevent` in [this thread](https://www.statalist.org/forums/forum/general-stata-discussion/general/1671714-verifying-parallel-trends-in-did-analysis), but there was limited discussion on `xtevent` itself.

I also switched keywords such as "pre trends" and "event study" and found no additional discussion on `xtevent`. Should I look for discussion on event studies in general and find potential changes we might want to make to `xtevent`?

Thanks!

**Comment by jorpppp** [comment]
@rayhuang11. Thanks, I don't think we need to search for additional threads or mentions of "event studies". There is a different methodology called "event study" in finance so if you use that search term you'll get a lot of threads unrelated to panel event studies.

I will post to Statalist about the new version and then we'll close this issue.

**Comment by jorpppp** [comment]
Here's the new Statalist post @SimonFreyaldenhoven 

https://www.statalist.org/forums/forum/general-stata-discussion/general/1672952-xtevent-stata-module-to-estimate-and-visualize-linear-panel-event-study-models-updated-on-ssc

I'll keep an eye out on Statalist to bring questions, bugs, and feature requests to Github.

**Comment by jorpppp** [comment]
Summary: In this issue we posted about the `xtevent` updated on Statalist. We also checked if there were any bugs or feature requests there.
