### ISSUE TITLE
Imputation of event-time dummies occurring when not specified

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#68]
Per [comment](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185027437) in issue #15, the endpoints correctly follow the specification/no specification of the `impute` option, but in the case of the event-time dummies, they are always being imputed.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero  will check the conditionals in `_eventgenvars` to make sure this issue does not occur.

**Comment by jorpppp** [comment]
To avoid Git conflicts, @Constantino-Carreto-Romero  will not create a commit here until the issues in #63  and #64 have been solved and the branches have been merged.

**Comment by jorpppp** [comment]
> To avoid Git conflicts, @Constantino-Carreto-Romero will not create a commit here until the issues in #63 and #64 have been solved and the branches have been merged.

#63 and #64  have been merged.

**Comment by Constantino-Carreto-Romero** [comment]
The following code snippet helps verify the correct imputation/no imputation of the event-time dummies:
```
use "https://github.com/JMSLab/xtevent/blob/main/test/example31.dta?raw=true", clear
*no imputation
cap drop *_k*
xtevent y, panel(i) t(t) policyvar(z) window(3) nodrop
```
For instance, for unit 1, event-time dummies look like this:
![noimp](https://user-images.githubusercontent.com/36095845/181782029-37b171c1-8b5c-49bb-a37b-9add6780693a.png)

```
*imputation 
cap drop *_k*
xtevent y, panel(i) t(t) policyvar(z) window(3) nodrop impute(nuchange)
```
![imp](https://user-images.githubusercontent.com/36095845/181782083-f29e0e19-5d95-40c3-b783-aaa606d3ebfc.png)

**Comment by jorpppp** [comment]
@veli-m-andirin this is a bug that you pointed out and we fixed.
