### ISSUE TITLE
reported mean in the plot not calculated with the imputed policy variable

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#69]
Per [comment](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185027437) in issue #15, when the option `impute` is specified, the reported mean in the plot is not calculated with the imputed version of the policy variable. Also check if the mean calculation follows [comment ](https://github.com/JMSLab/xtevent/issues/15#issuecomment-1185847554)in issue #15.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will check `_eventols` and `_eventiv` to make sure that the calculation of the mean of the dependent variable at baseline uses the imputed policy variable to identify the baseline. 

To avoid Git conflicts, @Constantino-Carreto-Romero will not create a commit here until the issues in https://github.com/JMSLab/xtevent/pull/63 and https://github.com/JMSLab/xtevent/pull/64 have been solved and the branches have been merged.

**Comment by jorpppp** [comment]
> To avoid Git conflicts, @Constantino-Carreto-Romero will not create a commit here until the issues in #63 and #64 have been solved and the branches have been merged.

#63 and #64  have been merged.

**Comment by Constantino-Carreto-Romero** [comment]
Now the reported mean in iv settings accounts for the imputed policy variable. The correction consisted only of changing a temporary variable. There still remains the correction in the case of _eventols.

**Comment by jorpppp** [comment]
@veli-m-andirin this an issue you pointed out.

**Comment by veli-m-andirin** [comment]
Thanks @jorpppp. On https://github.com/JMSLab/xtevent/issues/69#issuecomment-1206678699: Could you please clarify if this was a question?

**Comment by jorpppp** [comment]
Yes @veli-m-andirin, we were just letting you know that these issues had been resolved. Thanks again for pointing them out!
