### ISSUE TITLE
Inclusion of endpoints in the plot when adjusting with a trend

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#70]
After running this code snippet, where we are adjusting with a trend by ols method:

```
use "https://github.com/JMSLab/xtevent/raw/main/test/example31.dta", clear
xtevent y, panelvar(i) timevar(t) policyvar(z) window(5) trend(-3, method(ols))
xteventplot, ytitle("Coefficient") xtitle("Event time")
```
The following plot is produced:
![1 ](https://user-images.githubusercontent.com/36095845/180060708-fa8f71c3-6a59-4f9c-ac91-d1e32d82480d.png)

Endpoints should not be included in the plot.

**Comment by jorpppp** [comment]
@jorpppp  will check why the code that suppresses the endpoints when the `trend` option is used is not active here.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will check this.

**Comment by Constantino-Carreto-Romero** [comment]
Now endpoints are excluded in the plot if trend adjustment is specified. The problem showed up because endpoint exclusion was happening only if suboption `saveoverlay` was specified, but it should happen as long as the `trend` option is specified. I also ran the test file to check if the changes caused any problems.

**Comment by jorpppp** [comment]
Summary: In this issue we checked a bug with displaying the endpoints with the `trend` option,

Thread continues in #80
