### ISSUE TITLE
Clarify that some matrices are not generated unless the -trend- option is used

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#71]
Per comment in #7: https://github.com/JMSLab/xtevent/issues/7#issuecomment-1191841866
we want to clarify that `e(mattrendy)` and `e(mattrendx)` are only generated when the `trend` option is used.

**Comment by rayhuang11** [comment]
Summary: in `xtevent.sthlp` we clarified that `e(mattrendy)` and `e(mattrendx)` are only generated when the `trend` option is used.
