### ISSUE TITLE
Question about smoothest path

### ISSUE THREAD

**Issue by veli-m-andirin** [JMSLab/xtevent#72]
@jorpppp @Constantino-Carreto-Romero,

I had a question about the smoothest path. 

I think the object k [here](https://github.com/JMSLab/xtevent/blob/357b39e374e560705676b84b9ee6163dc0e765c7/xtevent/xteventplot.ado#L630-L633) corresponds to k on [this page](https://scholar.harvard.edu/files/shapiro/files/eventstudy.pdf#page=11), i.e. it should run from -G -L_G - 1 to M + L_M. Instead, it runs from 0 to p-1 where p is the number of event-study coefficients we estimated. It is further divided by p-1. The "shifting" seems to be harmless, when for instance I let k run from 1 to p, nothing seems to change. However, if I remove the normalization by p-1, then the smoothest path changes. 

Do you know why this "shifting" (i.e. from -G -L_G -1 to 0) and division by p-1 should work (and are needed)?

@jmshapir fyi.

**Comment by veli-m-andirin** [comment]
Also, a related suggestion/an item to wishlist: I think it would be nice to have a mathematical vignette that lays out how the smoothest path problem is solved in the code, detailing the approach used.

**Comment by jmshapir** [comment]
> Also, a related suggestion/an item to wishlist: I think it would be nice to have a mathematical vignette that lays out how the smoothest path problem is solved in the code, detailing the approach used.

@veli-m-andirin I've made a note of this, thanks!

**Comment by SimonFreyaldenhoven** [comment]
@veli-m-andirin Thanks! to add my two cents:

> Do you know why this "shifting" (i.e. from -G -L_G -1 to 0) and division by p-1 should work (and are needed)?

I think conceptually neither the shift or division are needed, but any shift and/or division should work. You are essentially just playing with the basis of the polynomial space. 

I think of the division as just a normalization (it redefines the x-axis to run from 0 to 1). Under the hood I believe we use a barrier function in the implementation (though @jorpppp should correct me if I'm wrong). Normalizing the x-axis this way likely helps with numerical stability (e.g. the tuning parameters we have to choose default values for work better across applications)

The shift is a bit different and I agree is a somewhat arbitrary choice. My intuition is that finding polynomials in the [-1 to 1] range in the Wald region can give you a different result than finding polynomials in the [0 to 1] range for the same region.

It is a priori not clear to me which one "makes more sense". I believe we briefly played with this before and felt the current range resulted in slightly more natural paths in the examples we looked at. 

Having said all of that, this seems like a great suggestion:
> Also, a related suggestion/an item to wishlist: I think it would be nice to have a mathematical vignette that lays out how the smoothest path problem is solved in the code, detailing the approach used.

**Comment by chansen776** [comment]
@veli-m-andirin @SimonFreyaldenhoven is correct. Conceptually, anything should be fine. The movements are for numeric stability as high-order polynomials are not numerically well-behaved. We looked at scaling to the unit interval and the -1 to 1 interval at different points in time. All of these normalizations should return (up to numeric issues) the same results if every feature of the problem is adjusted appropriately. Specifically, because we are solving a constrained optimization problem and directly plugging in a solution to keep you on the ellipse boundary, any change in normalization also changes all of the constraints in non-trivial ways. My guess is that this is where differences would pop up.

**Comment by jorpppp** [comment]
@veli-m-andirin let me know if @SimonFreyaldenhoven 's and @chansen776 's answers make sense. If so, we may be able to close this issue.

**Comment by veli-m-andirin** [comment]
Thanks @SimonFreyaldenhoven @chansen776 for the explanations, these make sense to me. 

@jorpppp, I agree that we can close the issue. @SimonFreyaldenhoven @jorpppp do you think the following should be tackled in a separate issue:

> Also, a related suggestion/an item to wishlist: I think it would be nice to have a mathematical vignette that lays out how the smoothest path problem is solved in the code, detailing the approach used.

I think this would help both xtevent users in terms of clarification and eventstudyr developers.

**Comment by jmshapir** [comment]
Thanks @veli-m-andirin! I've made a note of [that suggestion](https://github.com/JMSLab/xtevent/issues/72#issuecomment-1200481941) in another repository.

**Comment by veli-m-andirin** [comment]
Thanks @jmshapir!

Summary: In this issue I asked the questions in https://github.com/JMSLab/xtevent/issues/72#issue-1320892821  regarding the smoothest path implementation in xtevent.  The answers are in https://github.com/JMSLab/xtevent/issues/72#issuecomment-1199579913 and https://github.com/JMSLab/xtevent/issues/72#issuecomment-1199638054.
