### ISSUE TITLE
2.1.0 Release

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#74]
@Constantino-Carreto-Romero can you please update release.txt and readme.md for the new release? 

Is there anything else you think we need to update before releasing? 

@rayhuang11 FYI

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero Please make the updates in a branch. That way we can hold off the updates until we are ready to release.

**Comment by jorpppp** [comment]
With #75 and #76 closed, we can continue working on the release! @Constantino-Carreto-Romero please let us know when you've updated the description files above.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have updated the files: readme.md, release.txt, and xtevent.pkg to reflect changes due to the new release. I also updated the release date in the ado files where the release date was mentioned. The release date I specified is August 1, 2022.

**Comment by jorpppp** [comment]
Thanks @Constantino-Carreto-Romero. I'll check these now.

**Comment by jorpppp** [comment]
Summary: In this issue we updated descriptive files for the upcoming release, xtevent 2.1.0
