### ISSUE TITLE
Upload v 2.1.0 to SSC

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#78]
xtevent 2.1.0 is now live on Github.

To bring to SSC I'll email Kit Baum. @Constantino-Carreto-Romero @rayhuang11 Do you have a copy of the email to Kit Baum about v 2.0.0? If so, do you think you can forward it to me? There's a gap in my email archive :(

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I'm sorry, I don't remember receiving a copy of that email. Just in case, I have looked for it but it seems I didn't receive it.

**Comment by jorpppp** [comment]
Ok, thanks @Constantino-Carreto-Romero

**Comment by jorpppp** [comment]
I sent the email to SSC.

**Comment by rayhuang11** [comment]
@jorpppp sorry for the late reply! I don't have any prior emails with Kit. Thanks.

**Comment by jorpppp** [comment]
The new release is now up on SSC. Statalist and Twitter announcements are pending.

**Comment by jorpppp** [comment]
The announcements will be up after we update the version info here. I'll go ahead and close and merge.

**Comment by jorpppp** [comment]
Summary: In this issue we tracked updates to -xtevent- on SSC following the 2.1.0 release.

**Comment by jorpppp** [comment]
Link to Twitter announcement: https://twitter.com/jorpppp/status/1557059501903298560
Link to Statalist announcement: https://www.statalist.org/forums/forum/general-stata-discussion/general/1677065-xtevent-stata-module-to-estimate-and-visualize-linear-panel-event-study-models-updated-on-ssc
