### ISSUE TITLE
Stata 14 option limits

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#8]
@jorpppp pasting the below from our earlier notes. If this is already addressed feel free to close, thanks!

> Apparently Stata 14 only allows for 70 options on a command, while the limit is higher in Stata 15 and afterwards. In -xteventplot- we interlace commands with comments, and Stata's parser thinks the comments are options for some reason. So the latest version of -xteventplot- with many graph appearance options is not working on Stata 14 or below.

**Comment by jorpppp** [comment]
Summary: In this issue we fixed a bug with the options in `xteventplot' that prevented the command from running in Stata 14 or earlier.
