### ISSUE TITLE
Some examples in the help file not working 

### ISSUE THREAD

**Issue by Constantino-Carreto-Romero** [JMSLab/xtevent#84]
On August 9, 2022, a user reported that some examples in the help file show message errors. The problem arises because those examples were not updated to account for the `impute` option implemented in version 2.0.0.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have corrected the problematic examples in `xtevent`'s help file to consider the `impute` option. In all those examples, I had to add `impute(nuchange)`. I had to correct examples in `xteventplot` as well. In the case of `xteventtest`, it did not include any example, so I added some of them. I also added click functionality to the examples, this helped me verify easily that they ran correctly.

**Comment by jorpppp** [comment]
Looks good, thanks @Constantino-Carreto-Romero.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have added some examples from the updated help files to the readme file.

**Comment by jorpppp** [comment]
Great, thanks @Constantino-Carreto-Romero. Can you start a PR with me as reviewer, please?
