### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#86]
We should make a new release with the updates from #84 and #85, since the examples in the helpfile from 2.1.0 may confuse many users.

- [x] @Constantino-Carreto-Romero , what should be the new version number?
- [x] @Constantino-Carreto-Romero and @rayhuang11 can you test that the examples from the readme and the helpfile, and the test file are working, please?
- [x] @Constantino-Carreto-Romero can you change version statements when necessary and add the user who pointed out the issue to the acknowledgements please? Also, please check if there are more users that have contributed and who are not mentioned yet.

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp after v2.1.0 we have not implemented new features and we have only resolved bugs (issue #70) and changed the documentation (issues #79 and #84), so the version would be 2.1.1. 
[Source](https://www.geeksforgeeks.org/introduction-semantic-versioning/).

**Comment by Constantino-Carreto-Romero** [comment]
@jorpppp I have updated version statements, indicating Aug 11, 2022, as the release date. 
I added to the acknowledgments all the users who have found bugs or recommended some feature that was implemented.

**Comment by jorpppp** [comment]
Looks good, thanks @Constantino-Carreto-Romero. Once @rayhuang11 and you conclude testing we can start a PR.

**Comment by Constantino-Carreto-Romero** [comment]
> * [ ]  @Constantino-Carreto-Romero and @rayhuang11 can you test that the examples from the readme and the helpfile, and the test file are working, please?

@jorpppp I have executed the examples from the readme, the help files, and the test file, and they ran correctly.

**Comment by rayhuang11** [comment]
@jorpppp @Constantino-Carreto-Romero everything ran correctly for as well. I think we can start a PR. Thanks!
