### ISSUE TITLE
Add default maximum polynomial order for smoothest line

### ISSUE THREAD

**Issue by jmshapir** [JMSLab/xtevent#9]
We want to add a maximum polynomial order for the smoothest line to ensure problem stability.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will familiarize himself with the smoothest line code.- Then he will modify the code to search for polynomials up to the 10th order, as agreed here: https://github.com/JMSLab/EventStudy/issues/169#issuecomment-948774090

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero will change this in the next commit after we close #24

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero these changes look good. The only extra change we need here is to document this maximum order setting in the helpfile.

**Comment by jorpppp** [comment]
@Constantino-Carreto-Romero. Thanks, we'll modify the helpfile a bit as agreed per meeting today.

**Comment by jorpppp** [comment]
Summary: In this issue we modified the maximum polinomial order allowed in the command for the smoothest line plot.
Thread continues in #26
